version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: expanders360-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project_vendor_matching
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6.0
    container_name: expanders360-mongodb
    restart: always
    command: ["mongod", "--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  vendor-matching-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expanders360-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_started
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: project_vendor_matching
      MONGODB_URI: mongodb://mongodb:27017/project_vendor_matching
      JWT_SECRET: supersecretkey
      JWT_EXPIRES_IN: 3600s
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - .:/usr/src/app
    working_dir: /app
    command: npm run start:dev


volumes:
  mysql_data:
  mongo_data:
